### ISSUE TITLE
General Comments

### ISSUE THREAD

**Issue by robloo** [maxkatz6/AvaloniaWinUI.ColorPicker#1]
I expect it isn't quite working although I won't have time to test your code.

https://github.com/maxkatz6/Avalonia.ColorPicker/blob/f17c75719d5b249452ab1388bb5aeced6cd057e4/src/Avalonia.ColorPicker/ColorHelpers.cs#L528

In my port I had to add the Floor function or the wrong sextant was calculated and the whole spectrum was off.

`int sextant = Convert.ToInt32(Math.Floor(hue / 60));`

Otherwise, the port looks good overall, would definitely add back the async bitmap generation though.

**Comment by robloo** [comment]
Here:
https://github.com/maxkatz6/Avalonia.ColorPicker/blob/f17c75719d5b249452ab1388bb5aeced6cd057e4/src/Avalonia.ColorPicker/ColorSpectrum.cs#L1015

In all related places I would clamp the values. C++ doesn't behave the same as C# when truncating to a byte and I hit some overflows using Convert.ToByte() or invalid values (zero) if using `(byte)` like you. I would change both FillPixelForBox() and FillPixelForRing to something like the below:

```csharp
bgraMinPixelData.Add(Convert.ToByte(Math.Clamp(Math.Round(rgbMin.B * 255.0), 0, 255))); // b
bgraMinPixelData.Add(Convert.ToByte(Math.Clamp(Math.Round(rgbMin.G * 255.0), 0, 255))); // g
bgraMinPixelData.Add(Convert.ToByte(Math.Clamp(Math.Round(rgbMin.R * 255.0), 0, 255))); // r
bgraMinPixelData.Add(255); // a - ignored
```

After, I bet your spectrum works properly ;)

**Comment by maxkatz6** [comment]
Thanks for these points! I will take a look on this weekends. Also I should enforce checked context just for case.

> would definitely add back the async bitmap generation though

For some reason async generation worked slower on my PC, don't remember specific numbers tho. 
And async-free implementation takes about 15-20ms for me. Keeping in mind that ColorPicker generates bitmap really rarely, I leaved it as is.
But for better performance I should consider implementing bitmap generation using Skia directly (Avalonia uses it by default), probably with its shaders, and keep old implementation as a fallback.
Actually, WinUI uses Composition API generation on newer SDKs, that I can't migrate, because there is no any equivalent in Avalonia yet.

**Comment by robloo** [comment]
Well, I wouldn't be blocking the UI thread for this but its totally up to you! I'll have the Async stuff in my port if you ever need to copy that in the future as well.

> Actually, WinUI uses Composition API generation on newer SDKs

Yes, I also have all of that commented out for the Uno port. It might be interesting to try the SpectrumBrush approach and Skia on Avalonia though.

**Comment by robloo** [comment]
Welp, at least for the first one you don't need to use Floor(). That was a mistake on my end. So take the second recommendation with a grain of salt :)

**Comment by robloo** [comment]
Here are some ideas for doing things better a few places. Since Avalonia is a cleaner/better design a lot of places it would be cool is some of these ideas found their way into Avalonia. Number 1, 5 is already done in the Windows Community Toolkit's ColorPickerButton. Number 4 and 3 should be done soon.

1. RGB and HSV channels are identified separately in most places. For example, HSV channels are represented by the `ColorPickerHsvChannel` enum. Since HSV is used as the primary representation internally there is no corresponding enum for RGB channels. In the control template, however, there are separate controls depending on the active color representation RGB/HSV. This means there is a duplication of a large number of controls. These could all be unified, for example, by referring to both hue and red as channel 1, etc. This greatly simplifies the effort required in the control template itself and removes duplicate controls. Instead, the same input controls can be used and only the active color representation set. Internal representation could add an enum for Channel1, Channel2, Channel3 and Alpha.

1. The 'ThirdDimension' slider really should not be named 'dimension'. 'Channel' is the standardized term so 'ThirdChannelSlider' would be a better choice. 'Components' is also the term used in control properties.

1. HSV color representation should be externally exposed by the color picker for those applications that require higher levels of precision. A new HsvColor struct should be added to the existing RGB struct already in WinUI.

1. The `ColorPickerSlider` could render its own background and be made a completely independent control. This would simplify the `ColorPicker` template and code-behind considerably.

1. Composting of the preview/slider backgrounds with a checkered background underneath can be done all at once in code-behind when the background image is calculated. This would remove several template parts and greatly simplify the overall template. The affect on performance should be minimal and not detectable.

**Comment by maxkatz6** [comment]
@robloo 
1. I see your point with layout simplification, but not sure, it really can give noticeable advantage apart from bit smaller xaml file. Although if WinUI ColorPicker will be updated in that way, I don't see any reason why I shouldn't do the same.
2. Same as #1
3. Makes sense for me.
4. Makes sense for me.
5. I recently removed quite a lot of code required to build checkered background and fade-in background, and replaced it with brushes/opacitymask declared in the XAML. It wasn't possible in UWP/WinUI, but possible in WPF/Avalonia, and I usually prefer moving UI logic to the xaml files, where it's possible. This also simplified control, but in another way.

**Comment by robloo** [comment]
> Although if WinUI ColorPicker will be updated in that way, I don't see any reason why I shouldn't do the same.

Avalonia has so many differences from WinUI I didn't think you were taking the Uno Platform approach of direct ports only. That is to say, I think Avalonia controls should be free to branch away and improve where WinUI will stay stagnant due to Microsoft's policies.

Do you have any concerns about replacing entirely the default style and rebasing this control on the Windows Community Toolkit version? https://github.com/windows-toolkit/WindowsCommunityToolkit/issues/3363. Ideally there should be two controls 'ColorPicker' and 'ColorCanvas' and the whole structure reworked.

If not, I can look at taking the code you have as a base and making the Community Toollkit changes on top of it. Ideally this would all find it's way into upstream Avalonia itself.

**Comment by maxkatz6** [comment]
The goal of this project for me was to test how easily it will be to port C++ WinUI control to C# Avalonia, that's why I avoided unnecessary modifications in user experience. And I didn't plan to spent a lot of time on this project.

But if you have some time for it, I will be happy to review and accept it.

Although I would replace SwitchPresenter with ContentControl+custom IDataTemplate implementation (alternative to template selectors). Or even replace ListBox+SwitchPresenter with a restyled TabControl, where headers' items control might have UniformGrid ItemsPanel.
And maybe makes sense to keep this another ColorPicker implementation in another project/package, so it will be possible to keep WinUI implementation for a while. ColorSpectrum and stuff can be moved to the shared project.

**Comment by robloo** [comment]
The port to Avalonia has started. I used some of your ideas for `ColorSpectrum` and will also use a tiling brush for the checkered backgrounds to simplify quite a few things alter on. Overall though there is no point keeping this issue open. The lesson's learned mentioned here are being applied upstream.

Great work on this port! It was a big help with some questions porting the `ColorSpectrum` from UWP to Avalonia.
